kumuluzee:
  name: tt-customers
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/CustomersDS
      connection-url: jdbc:postgresql://127.0.0.1:5435/customer
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379

rest-properties:
  external-services:
    menu-service:
      enabled: true