apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customers-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - image: tabletopltd/tt-customers
        name: customers
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-customers:5432/customer
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://localhost:32696
        ports:
        - containerPort: 8084
          name: server
          protocol: TCP
